### ISSUE TITLE
RFE: allow knockout_prefix

### ISSUE THREAD

**Issue by jelmd** [railsconfig/config#101]
Is it possible to use DeepMerge::DEFAULT_FIELD_KNOCKOUT_PREFIX per default, or at least make it possible to use it?

Problem is, that with the current processing it is not possible to remove/replace elements in an array.
Since '--' is a very uncommon prefix for any values, I guess enabling it by default doesn't cause any problems.

E.g.: defaults.yml
```
bla:
  - fahsel
```
and settings.yml
```
bla:
  - --fahsel
  - foo
```
should result into { bla => [foo] }

Also it would be nice, if embedded doc splitting would be allowed ('---'). This way one could get an easy workaround for replacements. E.g. settings.yml:
```
bla: !str
---
bla:
  - foo
```

**Comment by pkrefta** [comment]
I'm not entirely sure but this is probably a question for YAML parser guys rather than gem authors.

**Comment by fredwu** [comment]
I would like a bit more feedback and suggestions on this one, let's keep the conversation in #66. :)
