### ISSUE TITLE
Read environment variables

### ISSUE THREAD

**Issue by stefanahman** [railsconfig/config#108]
Hi, I wonder if it is possible to do the following:
```bash
SETTINGS_I_LIKE_CATS="true" be rails c
```
and then recover the variable by:
```ruby
Settings.i_like_cats # => "true"
```

**Comment by fredwu** [comment]
It is certainly possible, would you or anyone like to have a crack and submit a pull request? ;)

**Comment by vinceve** [comment]
I would like to take a look at this. Wouldn't it be better to have some kind of prefix for env variables. For example:

```ruby
Settings.env.i_like_cats # => "true"
```
