### ISSUE TITLE
undefined method `preload' for RailsConfig::Integration::Rails::Railtie:Class (NoMethodError)

### ISSUE THREAD

**Issue by navaneeth** [railsconfig/config#111]
I am trying to load rails_cofig before rails loads. Followed the instructions give in the README. Here is my `application.rb`

```
require File.expand_path('../boot', __FILE__)

require 'rails/all'
require 'rails_config'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)
RailsConfig::Integration::Rails::Railtie.preload

module Api
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de

    # Do not swallow errors in after_commit/after_rollback callbacks.
    config.active_record.raise_in_transactional_callbacks = true
  end
end
```

But this fails with error

```
undefined method `preload' for RailsConfig::Integration::Rails::Railtie:Class (NoMethodError)
```

Rails version - `Rails 4.2.3`
Ruby version - `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]`

**Comment by j2d3** [comment]
I'm having the same problem with the same version of Rails and Ruby

**Comment by fredwu** [comment]
The two lines below need to be executed in your `Application` class according to the README, right? You had them executed before outside of the class.

```ruby
Bundler.require(*Rails.groups)
RailsConfig::Integration::Rails::Railtie.preload
```

**Comment by pkuczynski** [comment]
Instead of loading Config before loading Rails, could you describe your usage scenario? I have already made Config available on the earlier Rails loading stages (like to be able to use it in database.yml), so maybe your scenario is general enough that we can provide a general solution for this?

**Comment by RoLoTo** [comment]
Move the two lines into your Application class block in application.rb.  I found I had to change "RailsConfig" to "Config" to get it to tie in.  So:

Bundler.require(*Rails.groups)
RailsConfig::Integration::Rails::Railtie.preload

becomes:

Bundler.require(*Rails.groups)
Config::Integration::Rails::Railtie.preload

**Comment by YaroSpace** [comment]
I am having the same problem.  Not sure if this is a correct way to go, but moving the line `          config.before_configuration { preload }` after the `preload` method definition in the `config/integration/rails.rb` worked for me.

**Comment by giorgian** [comment]
My scenario: config used in a Rails engine initialiser.

Everything works fine in the Rails app, but rake test inside the engine fails. YaroSpace's fix solves the problem.

**Comment by YaroSpace** [comment]
I am also using it in the engine and also in the wrapper apps.
This is how I do it:

1. I require the config in the wrapper app (by including into Gemfile).  This way the gem gets initialized and the app specific config is picked up.
2. In the engine, I have a custom initializer, which reads engine specific config and prepends it to Settings. (`Settings.prepend_source!(..); Settings.reload!`).  So, the engine config settings are picked up, when the engine is initialized.

**Comment by giorgian** [comment]
Thanks, I'll experiment with that, although in my case I don't foresee using engine specific configuration, just the wrapper ones (and of course the test/dummy ones).

**Comment by pkuczynski** [comment]
I updated the rails integration code like @YaroSpace suggests and pushed to the repo (no new gem release yet, so you would have to test it referencing github repo).

The description in README about manually loading preload should not be valid anymore IMHO, as the config should load by default before Rails application configuration. See #145

If someone could test and confirm, it would be awesome!

**Comment by chrishough** [comment]
I recently started getting the same error:
```
bundler: failed to load command: ./bin/rails (./bin/rails)
NameError: uninitialized constant Config::Integration
```
Example Code
```
# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module WhiplashIntegrations
  class Application < Rails::Application
    Bundler.require(*Rails.groups)
    Config::Integration::Rails::Railtie.preload
```

However, if I take this out completely it appears to work.  Do we need this setting anymore?

**Comment by pkuczynski** [comment]
This seems to be fixed now. Please comment if you feel it is still not working properly.
