### ISSUE TITLE
Option to Add Settings to Rails.configuration 

### ISSUE THREAD

**Issue by sshaw** [railsconfig/config#112]
Instead of (or in addition to) putting options into `SomeConstant` this option would put them into `Rails.configuration`.

Aside from being The Rails Way™ to store application config, it can also make things easier on those migrating to RailsConfig.

What do you think?

**Comment by fredwu** [comment]
This could potentially create conflicts though... what if you have a config item the same name as one of the `Rails.configuration` ones?

**Comment by sshaw** [comment]
>  ... what if you have a config item the same name as one of the Rails.configuration ones?

I'd imagine that majority of people would be use a single config method and this would be an edge case that can be handled via something like:  `Settings.on_load_conflict(:raise)`, (or `:overwrite`, `:skip`) though `:raise` should be the default.

Or, maybe there's a more `Config` like way to do it. Though that seems about right.

**Comment by sshaw** [comment]
> Or, maybe there's a more Config like way to do it. 

```ruby
Config.setup do |cfg|
  # Can also be Sinatra.settings
  # Requires code change of course
  cfg.const_name = Rails.configuration 
  cfg.on_conflict = :skip
end
```

**Comment by pkuczynski** [comment]
Rails.configuration is more to configure Rails, not to store general application settings. Please note that current trend is to move all gems configuration to `config/initializers/gem_name.rb`. So I would personally keep Config as a separate, easily accessible object.

**Comment by vinceve** [comment]
I would like to follow @pkuczynski in this one. Rails.configuration is to configure rails internals.

**Comment by sshaw** [comment]
> Rails.configuration is more to configure Rails, not to store general application settings
> ...
> Rails.configuration is to configure rails internals.

Not true. 

`Rails.configuration`  allows for custom, application specific configuration since 3.0 or 3.2 I think. Are you aware [of this](http://guides.rubyonrails.org/configuring.html#custom-configuration)?

[The examples in Config's README](https://github.com/railsconfig/config#accessing-the-settings-object) can be written in Rails < 4.2 out the box like this:

```ruby
# application.rb
config.my_config_entry = OpenStruct.new
config.my_config_entry.some_entry = "foo"

# somewhere else
Rails.configuration.my_config_entry
Rails.configuration.my_config_entry[:some_entry]
```

With Rails 4.2, this was made easier with the addition of [custom_configuration](https://github.com/dhh/custom_configuration). 

So to try to put a point on all of this :smile: 

`Config` has some nice features that can enhance Rails native approach. The problem is existing applications have perfectly valid code that depends on things like: 

```ruby
Rails.configuration.my_app.payment_window = 5.days
```

If one wants to migrate to `Config`, they have to change all of that to:
 
```
SomeConstant.my_app.payment_window = 5.days
``` 

:person_frowning:.

**Comment by vinceve** [comment]
Ok. I didn't know about that. I'll investigate it some more so that I'm up2date! Thanks for you clarifying response!

**Comment by vinceve** [comment]
@sshaw I guess it would be possible to do this:

```ruby
# application.rb
config = Settings
```

I'm not sure of this. We would need to investigate this.

**Comment by pkuczynski** [comment]
Populating settings back to Rails.configuration is possible but would requite quite some effort and I think it's pointless. Although Rails allows custom configuration for their default Rails.configuration object, one should decide if the default Rails behaviour is enough for him, or he would rather need some extra functionality and use gem like Config (or many others available).

If one decide to use 3-rd party gem to manage his application configuration, he should stick to the gem's way not Rail's way which is clearly insufficient ;)

It's not that we breaking the way Rails works. But trying to manage Rails.configuration object shared with Rails internals is very challenging and IMHO not worth the effort.
