### ISSUE TITLE
Template file name is incorrect?

### ISSUE THREAD

**Issue by KOBA789** [railsconfig/config#115]
In 1.0.0.beta1, when I run `rails g config:install` I can see an error:
```
Could not find "config.rb" in any of your source paths. Your current source paths are:
{...omitted...}vendor/bundle/ruby/2.2.0/gems/config-1.0.0.beta1/lib/generators/config/templates
```

In [`install_generator.rb`](https://github.com/railsconfig/config/blob/f67cee3b351377b4cf3a9dc9eb4952bb6dde38ab/lib/generators/config/install_generator.rb) filename is described as `config.rb`.
However there is not `config.rb` but [`rails_config.rb`](https://github.com/railsconfig/config/blob/f67cee3b351377b4cf3a9dc9eb4952bb6dde38ab/lib/generators/config/templates/rails_config.rb) in template directory.

**Comment by fredwu** [comment]
Thanks! I've just pushed `1.0.0.beta2` that fixed this issue. :)
