### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by shlima** [railsconfig/config#117]
Hello, could you please provide a changelog to us. For me, for example, `Settings` and `Config` constants are not defined in v1.0.0.beta3

**Comment by fredwu** [comment]
Yep, will do! What do you mean by `Settings` and `Config` are not defined?

**Comment by shlima** [comment]
I meant the following error:

```
uninitialized constant Config (NameError)
```

**Comment by cratz** [comment]
@shlima I had the same issue. 
Just change 
```gem 'rails_config'```
to
```gem 'config'```
in your Gemfile.

**Comment by shlima** [comment]
@cratz I have been already done this since 1.0.0.beta1

**Comment by fredwu** [comment]
@shlima What are your ruby and rails versions?

**Comment by shlima** [comment]
@fredwu Rails 4.2.3, ruby 2.2.1p85

**Comment by shlima** [comment]
Hmm, after running `bundle update` I actually see `config (0.0.1)` in my Gemfile.lock

**Comment by fredwu** [comment]
Yep you'd need to specify beta. :)
