### ISSUE TITLE
Option overwriting doesn't work (for me, at least)

### ISSUE THREAD

**Issue by smoofles** [railsconfig/config#12]
Hiya, 

I'm using an optional YML file with additional options as well as changes to the existing ones, which is loaded if it exists (doing so via `Settings.add_source!("#{Rails.root}/config/lpl.yml")` in my app's initializer). The problem is that I have the following defined in settings.yml:

    lpl: 
      ..
      language_options:
        - de
        - en
      ..

while my own file has

    lpl: 
      ..
      language_options:
        - de
      ..

I was expecting the result to be that `Settings.lpl.language_options` would hold `["de"]`, yet it still holds `["de", "en"]`. Do I need to do anything besides 

    if File.exists?("#{Rails.root}/config/lpl.yml")
      Settings.add_source!("#{Rails.root}/config/lpl.yml")
      Settings.reload!
    end

when loading the additional settings in my initlializer? Or should I be unloading all settings and include all the settings in `lpl.yml`, not just the ones that would add to/overwrite stuff from `config.yml`? And if so—how? 

Thanks! :)

**Comment by DannyBen** [comment]
Hey guys - I bumped into the same problem today, and found this 5 year old ticket with a 1 year old open PR.... is this fix happening? Or should we just consider arrays as non overridables for now?

**Comment by vinceve** [comment]
Hey Danny,

I had the same problem and made a fix around the same time this was fixed. But after that the deepmerge was extracted in a separate gem. And as the deepmerge gem isn't updated in a long time. I guess it's not in there.

That's why I still have a fork where I implemented this feature. You can find it here: https://github.com/vinceve/rails_config

**Comment by DannyBen** [comment]
Thenks @vinceve - good to know. I am relying heavily on this config gem and its overrides. I hope to hear from one of the contributors about this ticket, to at least know whats the official policy in the canonical repository, and if there is a plan to change the current additive behavior.

**Comment by pkuczynski** [comment]
This has been fixed in #137
