### ISSUE TITLE
 Use RbConfig instead of obsolete and deprecated Config

### ISSUE THREAD

**Issue by s8186255** [railsconfig/config#121]
when rails c,warning as following appears
/home/***/.rvm/gems/jruby-9.0.3.0@global/gems/config-1.0.0/lib/config/compatibility.rb:1:in `<top>': Use RbConfig instead of obsolete and deprecated Config.
my config.rb in initialize directory:
Config.setup do |config|
  config.const_name = "Settings"
end

**Comment by endenis** [comment]
+1, I have the same problem (ruby 2.2.3p173, Rails 4.2.5)

**Comment by khelll** [comment]
+1

**Comment by jcarlson** [comment]
I started getting this warning when switching from MRI 2.2.2 to JRuby 9.0.4.0...

**Comment by jeremyhaile** [comment]
I am getting this bug on JRuby 9.0.1.0

**Comment by MityaLiu** [comment]
+1

**Comment by nadavshatz** [comment]
+1

**Comment by rdubya** [comment]
This doesn't appear to be an issue in newer versions of JRuby. I'm going to close this since version 2.0 will support only JRuby 9.2+

Feel free to reopen if anybody is still experiencing this issue on newer versions.

**Comment by pkuczynski** [comment]
@rdubya whenever closing issue, please assign to the latest milestone...

**Comment by pkuczynski** [comment]
Should we mention in README, that we only support JRuby 9.2+ from 2.0?

**Comment by rdubya** [comment]
Sorry about that, I'll keep that in mind for the future. I figured since it doesn't look like JRuby is officially supported at this point that the README didn't need updated. I was hoping to get JRuby added to the travis matrix at some point. Would it be ok to leave it off of the README until then?

**Comment by pkuczynski** [comment]
Sure! Just created #228 to see how it behaves.
