### ISSUE TITLE
NameError: uninitialized constant AppName::Application::Settings. Rails 4.2.5

### ISSUE THREAD

**Issue by jayzz55** [railsconfig/config#126]
Same as #44 but.
rails 4.2.5

**Comment by AmitPatel-BoTreeConsulting** [comment]
I am too facing same issue with 4.2.5

**Comment by 9mm** [comment]
Same

**Comment by pkuczynski** [comment]
I dbl checked that issue as well as #44 and I can not reproduce the problem. I created this basic example of Rails 4.2 application with Config installed: 

https://github.com/railsconfig/config-rails-4.2

It seems all is working without any issue. Please let me know what I am missing here or create PR for this repo to illustrate the issue your are experiencing...

**Comment by malakai97** [comment]
This is actually very bizarre:

```
5] pry(Config)> whereami

From: stuff/.bundle/ruby/2.3.0/gems/config-1.6.1/lib/config.rb @ line 55 Config.load_and_set_settings:

    54: def self.load_and_set_settings(*files)
 => 55:   require "pry"; binding.pry
    56:   Kernel.send(:remove_const, Config.const_name) if Kernel.const_defined?(Config.const_name)
    57:   Kernel.const_set(Config.const_name, Config.load_files(files))
    58: end

[6] pry(Config)> Config.const_name
=> "Settings"
[7] pry(Config)> Kernel.const_defined?(Config.const_name)
=> true
[8] pry(Config)> Kernel.send(:remove_const, Config.const_name)
NameError: constant Kernel::Settings not defined
from (pry):7:in `remove_const'
```

**Comment by pkuczynski** [comment]
This issue does not seem to be valid anymore. Closing. Please comment if you feel it should be re-opened.

**Comment by codertyler** [comment]
Facing this issue when upgrading my Rails app from 4.1.14 to 4.2.10
