### ISSUE TITLE
Overloading with nulls

### ISSUE THREAD

**Issue by davemitchell** [railsconfig/config#13]
I was expecting to be able to "unset" a property in an overriding config file.  For example, consider the following:

In `config/settings.yml`
    name: Admin
    email: root@foo.com

In `config/settings/development.yml`
    name: Nobody
    email: null

However, it looks like instead of unsetting the value, the derived property is untouched.
That is, the above case yields:
    Settings.name # => Nobody
    Settings.email # => root@foo.com

Rather than what I was expecting:
    Settings.name # => Nobody
    Settings.email # => nil

Bug, or feature?

**Comment by toncid** [comment]
Hello, 

What's the status of this issue? It's still occurring and overriding with a blank value doesn't affect the original value.

Thanks!

**Comment by pkuczynski** [comment]
There is an open PR on deep merge gem: https://github.com/danielsdeleo/deep_merge/pull/20

**Comment by pkuczynski** [comment]
I made a mistake. In fact, https://github.com/danielsdeleo/deep_merge/pull/33 solves this issue, not https://github.com/danielsdeleo/deep_merge/pull/20
