### ISSUE TITLE
The newly added entries to .yml are not getting loaded

### ISSUE THREAD

**Issue by MonikaMahanthappa** [railsconfig/config#131]
I would like to know if there is any configuration that i'm missing. As the newly introduced entries to yml files are not loading even after the app restart. 

In our Gemfile

`gem 'config'`

config.rb

```
Config.setup do |config|
  config.const_name = "Settings"
end
```

I have even tried to load the files using `Config::Integration::Rails::Railtie.preload`. But even that does not help. But the entries are loaded when i explicitly make call `Settings.reload!` in the console. So i'm sure that yml configs are right. Any suggestion would be very helpful.

**Comment by tehandyb** [comment]
I'm having the exact same issue. My workaround was to put Settings.reload! inside config/application.rb:
`module myModule
    class Application < Rails::Application
        Settings.reload!
    end
end
`

**Comment by pkuczynski** [comment]
This is not needed. However settings file are per their nature static so we optimised towards application runtime and they are loaded only once when your application server starts. This means that when you modify yaml file, you need to restart the server.
