### ISSUE TITLE
Gem error using RVM ruby-2.0.0-p643

### ISSUE THREAD

**Issue by jorgevbo** [railsconfig/config#136]
Hi,

I'm getting next error after execute bundle install in Rails:

Gem::InstallError: config requires Ruby version >= 2.2.2.
An error occurred while installing config (1.1.0), and Bundler cannot continue.
Make sure that `gem install config -v '1.1.0'` succeeds before bundling.

I'm using default version en Gemfile:

gem 'config'

**Comment by ArtemDordovskiy** [comment]
I've fixed it by adding version

gem 'config', '1.0.0'

**Comment by DannyBen** [comment]
I am also getting this error, and also locked version to "< 1.1.0" - but this is not a fix.
I could not find anywhere in the changelog / readme that the compatibility changed to >= ruby 2.2.2 - so I guess this is an unintentional bug?

**Comment by philrosenstein** [comment]
Same problem here.  Ruby 2.2.1 does not satisfy dependencies..

**Comment by stefanahman** [comment]
@pkuczynski Add a new tag for Ruby version downgrade? Current master has no tag.

**Comment by pkuczynski** [comment]
Actually the current stable and maintained versions are listed here: https://www.ruby-lang.org/en/downloads/

* 2.1.9
* 2.2.5
* 2.3.1

Although Config does not require latest Ruby version and I made this change accidentally. I already fixed that on March 26th but did not released it, so let me do it now as v1.1.1

**Comment by pkuczynski** [comment]
Done. Please use version 1.1.1
