### ISSUE TITLE
Feature idea: ENV overrides when not on Heroku

### ISSUE THREAD

**Issue by jacquescrocker** [railsconfig/config#138]
I'm using Config on an environment that isn't heroku. Doesn't look like there's a good way to utilize `use_env` config, since ENV vars on linux can't have `.` in them.

Idea: automatically check for ENV vars with `__` in place of the `.` (if there's none already found with the `.`)

example:

```
ENV['Settings__section__size'] = 1
ENV['Settings__section__server'] = 'google.com'
```

**Comment by pkuczynski** [comment]
Fixed by #125. Released in version 1.2.0
