### ISSUE TITLE
Add support for Ruby range type in YAML configuration files

### ISSUE THREAD

**Issue by vanhuyz** [railsconfig/config#140]
Hi,

I think it would be more helpful if we could define a range in the configuration files.
Currently, it returns a string instead of a range.

For example, 

``` yaml
digits: 0..9 
```

``` bash
Settings.digits # => a string "0..9", not a range
```

Even with embedded Ruby, the result is still the same:

``` yaml
digits: <%= (0..9) %>
```

``` bash
Settings.digits # => a string "0..9"
```

**Comment by pkuczynski** [comment]
I think this is pretty good idea. I will try to pick it up in the future, unless there is some other volunteer?

**Comment by pkuczynski** [comment]
Have you tried the standard YAML feature http://yaml.org/YAML_for_ruby.html#ranges

```yaml
digits: !ruby/range 0..9
```

I know it is not the cleanest one, but already supported by YAML parser in Ruby...

**Comment by vanhuyz** [comment]
@pkuczynski: Yes, it works! Thank you!

**Comment by pkuczynski** [comment]
I must say it's far from being ideal and readable, but I am not sure if it's worth to monkey patch YAML loader or process the settings using regexp? What you think?
