### ISSUE TITLE
Freeze strings automatically?

### ISSUE THREAD

**Issue by toncid** [railsconfig/config#150]
Hello,

Ever considered making config strings frozen by default? 

By not freezing them, subtle issues are possible with the config object:

``` ruby
my_config = Settings.my_config
# some lines later...
my_config << 'aaa'  # changes the Settings field silently
```

I strongly believe that configuration fields should be immutable, so I'm wondering why they're not.

**Comment by pkuczynski** [comment]
Well, we could freeze them up, but the idea was, that config can be updated live, without reloading the app.

**Comment by toncid** [comment]
Not much of a config, if it behaves like a variable, huh?
Shouldn't the config object represent read-only, constant-like fields that can be modified externally (in .yml files), but remain unchanged while the app is running?

**Comment by pkuczynski** [comment]
Well, probably it should. I am planning to rewrite this part of code also in the light of #122. I believe Config should be a singleton, don't you?

**Comment by toncid** [comment]
I agree. I didn't even think that calling `Settings.my_config` actually refers to a mixed-in module on the `Object` class.

**Comment by pkuczynski** [comment]
@rdubya what you think?

**Comment by rdubya** [comment]
I think we could probably freeze them by default. I think the plan for MRI 3 is for all strings to be frozen by default. Should this apply to all types and not just strings, I guess that would potentially be a breaking change for anybody that does modify them at run-time. I agree that when I think of this gem, I see it as a way of defining static values on startup. There are other ways to generate global variables if somebody is just using this gem as that.

**Comment by toncid** [comment]
Well, you could consider adding a config flag and start preparing for the new scenario:

```
Config.setup do |config|
  config.const_name = 'Settings'
  config.freeze_values = true  # otherwise, defaults to false
end
```

**Comment by pkuczynski** [comment]
@toncid would you like to come up with a PR for this? I shifted away from Ruby to Node.js so changing this would be quite an effort for me...

**Comment by toncid** [comment]
@pkuczynski I have checked how freezing strings cloud be done and I see no simple way of achieving it. The gem relies on Ruby's built-in `YAML.load`, which does not offer such functionality and switching to a custom YAML parser is probably not feasible.

**Comment by pkuczynski** [comment]
Yeah, custom YAML parser would not be a good idea... But then if there is no easy way of achieving this, I guess we should close this issue?

**Comment by toncid** [comment]
Yes, probably we should. :) Thanks!
