### ISSUE TITLE
Disable embedded ruby

### ISSUE THREAD

**Issue by Persader** [railsconfig/config#152]
Hi,

I'm looking for a way to disable embedded ruby in configuration files. Is it actually possible ? If not, could you please add an option to ?

Many thanks

Leo

**Comment by pkuczynski** [comment]
What exactly do you mean? I don't follow you...

**Comment by Persader** [comment]
Considering this yaml file : 
key : "<%= datas['actor'] %> is following you"

When I load it with Config.load_and_set_settings(config_files) it raises an error :
Uncaught exception: undefined local variable or method `datas' for main:Object

I would like to load this file without evaluating datas['actor'] bevause I evaluate it later with local datas.

**Comment by pkuczynski** [comment]
Feels like you are missusing Config. Why don't you store this string in i18n?

**Comment by Persader** [comment]
You're right but I'm working on an existing project so this was wrote like that :(

I will extract all theses properties to another file.

**Comment by pkuczynski** [comment]
I really think it is better to cut it off config, as they don't look like a config related values :)

**Comment by Persader** [comment]
Yes you're right but it requires a long time refactoring :) I add it to my TODO list ;)

For the moment I just need to import some yaml config file from another project.
