### ISSUE TITLE
Need overwrite_arrays options feature release

### ISSUE THREAD

**Issue by bastengao** [railsconfig/config#153]
I see overwrite_arrays options feature in master, but not released. Because dependency gem deep_merge overwrite_arrays is false default, I can't set that option in other ways.

**Comment by pkuczynski** [comment]
I released this as version 1.3.0 on September 14th. Are you sure you are using correct version?

**Comment by bastengao** [comment]
Excuse me, I only saw the last release of github is `1.2.1`. Thanks 😸

**Comment by pkuczynski** [comment]
Forgto to make GH release :) Fixed now :)
