### ISSUE TITLE
Inconsistent documentation for ENV prefix

### ISSUE THREAD

**Issue by smoyth** [railsconfig/config#162]
I believe these are the correct settings for bash-style env vars:

```
# Initializes the config gem
Config.setup do |config|
  config.use_env = true
  config.env_prefix = 'SETTINGS'
  config.env_separator = '__'
  config.env_converter = :downcase
  config.env_parse_values = true
end
```

Note that env_prefix needs to be all uppercase. What is there now is `Settings`, which doesn't work for me.

Thanks for such a great gem!

**Comment by pkuczynski** [comment]
@rdubya what you think?

**Comment by rdubya** [comment]
Looks like we should probably fix the default since the docs already say that the default is in all caps. That might be a breaking change though.

**Comment by pkuczynski** [comment]
Bash variables do not need to be in all upper case. You can easily define them in any case. But you are right, a common practice is to set them all upper case. I just updated the generator by doing all upper case definition - this way we will not affect current users.

Please have a look at #246 and let me know if this is enough in your opinion to close this ticket?
