### ISSUE TITLE
rails g config:install's .gitignore

### ISSUE THREAD

**Issue by gipcompany** [railsconfig/config#163]
Below is just a tiny question.

`rails g config:install` introduces the following `.gitignore`'s diff.

```
diff --git a/.gitignore b/.gitignore
index 48fb168..fa705e2 100644
--- a/.gitignore
+++ b/.gitignore
@@ -15,3 +15,7 @@

 # Ignore Byebug command history file.
 .byebug_history
+
+config/settings.local.yml
+config/settings/*.local.yml
+config/environments/*.local.yml
```

However, to be more correct, slashes on the top are necessary like below, aren't they?

```
diff --git a/.gitignore b/.gitignore
index 48fb168..fa705e2 100644
--- a/.gitignore
+++ b/.gitignore
@@ -15,3 +15,7 @@

 # Ignore Byebug command history file.
 .byebug_history
+
+/config/settings.local.yml
+/config/settings/*.local.yml
+/config/environments/*.local.yml
```

**Comment by pkuczynski** [comment]
I don't think they are. The paths would be relative to location of `.gitignore`.

**Comment by gipcompany** [comment]
@pkuczynski 

Oops, I think this issue seems not cleared yet. Just to make sure your intension, to let the paths relative to location of `.gitignore`, the slashes are necessary. Do you know the difference between the case w/ and w/o slashes on the top?
