### ISSUE TITLE
Can't put ActiveSupport::Duration to settings

### ISSUE THREAD

**Issue by dzjuck** [railsconfig/config#168]
May i put `ActiveSupport::Duration` to settings?

```ruby
#settings.yml
timeout: <%= 1.hour %>

> Settings.timeout
=> 3600
> Settings.timeout.class
=> Fixnum
> 1.hour.class
=> ActiveSupport::Duration
> Settings.timeout.ago
=> NoMethodError: undefined method `ago' for 3600:Fixnum
```

I already found a way to use a value from settings as Fixnum:
```ruby
Settings.timeout.seconds
=> 3600 seconds
Settings.timeout.seconds.class
=> ActiveSupport::Duration
Settings.timeout.seconds.ago
=> Sat, 25 Mar 2017 14:08:32 UTC +00:00
```

But access without additional method will be nicier.

**Comment by pkuczynski** [comment]
Config only accepts basic types. Putting `<%= 1 hour %>` would actually evaluate it into the value 3600 as you observed. So you would have to call `ActiveSupport::Duration.parse(Settings.timeout)` to get what you expect...

**Comment by dzjuck** [comment]
@pkuczynski Thanks for explanation. Should i close this issue?

**Comment by pkuczynski** [comment]
I believe so. RailsConfig only works on basic types. We could consider extending the syntax to support form:

```
# settings.yml
timeout: 1.hour
week: 7.days
```

If you think it is worth it? It would not support any kind of operations and would allow entering basic values. Not sure if that's worth the effort? It would also slow down a bit config load as it would need to regexp every setting searching for that...

Another option would be to play around with native YAML techiques to store custom objects (http://yaml.org/YAML_for_ruby.html#objects):

```
# settings.yml
timeout: !ruby/object:ActiveSupport::Duration 1.day 
```

Not very elegant...
