### ISSUE TITLE
Support booleans with env_parse_values

### ISSUE THREAD

**Issue by adamkiczula** [railsconfig/config#178]
This is more of a feature request, but if you have a config like `something: true` and then override it with an ENV variable `SETTINGS__SOMETHING=false` the setting becomes "false" which is still truthy. I wonder if there's an eloquent way to make these values a boolean, or if that isn't an option, update the readme to explicitly call out not to use boolean configs as there will be no way to override them unless your code treats them like strings.

**Comment by stephenhmarsh** [comment]
fwiw i have used this erb pattern successfully in yml files:

`something: <%= ENV['SOME_FALSE_VARIABLE'] %> || true`

it will correctly read that variable as `false`, and not something truthy like `"false"`

**Comment by mjgiarlo** [comment]
@adamkiczula @stephenhmarsh See https://github.com/railsconfig/config/pull/180. Should be merged soon, and hoping 1.6.0 can be released thereafter.
