### ISSUE TITLE
Settings const name is not available right after Config.setup

### ISSUE THREAD

**Issue by kapso** [railsconfig/config#187]
I am trying to access `Settings` const name in `config.rb` right after `Config.setup`, but getting an error?

`*/initializers/config.rb`
```ruby
Config.setup do |config|
  config.const_name = 'Settings'
end

# Following results in an error - uninitialized constant Settings (NameError)
Settings.add_source!("#{Rails.root}/config/tune.yml")
Settings.reload!
```

**Comment by pkuczynski** [comment]
This should be fixed now. @kapso can you check again?

**Comment by pkuczynski** [comment]
This is not a valid way of doing, what you try to do. `add_source` should be called outside of initializer...

If your case is still needed we could add an option `extra_sources` to add additional sources. But in general idea behind this gem was to stick with following pattern: https://github.com/railsconfig/config/blob/master/lib/config.rb#L58

**Comment by supremebeing7** [comment]
Since this is 1.5 years old I'm assuming this is probably resolved by now, but FWIW @kapso, you could create a separate initializer to load the `tune.yml` sources. I think something like this should work:

*/initializers/config.rb
```ruby
Config.setup do |config|
  config.const_name = 'Settings'
end
```
*/initializers/tune.rb
```ruby
Settings.add_source!("#{Rails.root}/config/tune.yml")
Settings.reload!
```

**Comment by pkuczynski** [comment]
Yes, that could be a workaround for now. Closing this until further interest from anybody...
