### ISSUE TITLE
const_name Override is not working

### ISSUE THREAD

**Issue by nazarhussain** [railsconfig/config#188]
Hi, 

I have following config in my file 

```
Config.setup do |config|
  # Name of the constant exposing loaded settings
  config.const_name = 'Settings2'

```
when called for configurations, it says; 

```
irb(main):004:0> Settings2
NameError: uninitialized constant Settings2
```
Although settings still persist in `Settings` constants and available. 

I am using Rails 5.1.4.

**Comment by pkuczynski** [comment]
I added Rails 5.1.5 to then testing scope in #200 and it seems it all works well. Could you check again please?

**Comment by rjayroach** [comment]
Same issue with Rails 6.0.0.beta1

**Comment by pkuczynski** [comment]
@rjayroach and @nazarhussain is still an issue for you?

**Comment by nazarhussain** [comment]
@pkuczynski With following configurations it works for for me. 

```
ruby '2.4.2'
gem 'rails', '~> 5.2.1'
gem 'config', '~> 2.0'
```

**Comment by pkuczynski** [comment]
I guess we can close it then :)

**Comment by Riveascore** [comment]
This is still broken for me. I tried @nazarhussain's approach, didn't work.

**Comment by cjlarose** [comment]
@Riveascore feel free to open a new issue. If you can, please provide a complete test project that reproduces the issue. That'll help a lot for debugging the issue.
