### ISSUE TITLE
NameError for Kernel::Settings when the global const Settings is already defined.

### ISSUE THREAD

**Issue by malakai97** [railsconfig/config#189]
This bug occurs in line 55 of lib/config.rb when the constant `Settings` is already defined, but somehow Kernel::Settings is not. I am not 100% clear on how to achieve this scenario. The culprit in my setup seems to be the configliere gem which is loaded by a dependency of my project.

The specific issue is that `const_defined?` has default behavior (`inherit=true`) that also searches Object.

**Comment by nerfologist** [comment]
Also having an issue with this gem in combination with the `create-api-gem` which I believe to be the same as this one.

The `create-api-gem` also happens to define a `Settings` constant.

This is the error
```
         1: from /Users/myuser/.rvm/gems/ruby-2.6.1@myprojectgemset/gems/config-1.7.1/lib/config.rb:56:in `load_and_set_settings'
/Users/myuser/.rvm/gems/ruby-2.6.1@myprojectgemset/gems/config-1.7.1/lib/config.rb:56:in `remove_const': constant Kernel::Settings not defined (NameError)
```

**Comment by pkuczynski** [comment]
We dropped from defining config as Kernel variable. @nerfologist and @malakai97 can you check if this issue is still valid?

**Comment by malakai97** [comment]
I no longer have the configuration that first ran into this issue, but I can take a look if you tell me which branch/tag/commit to pull.

**Comment by pkuczynski** [comment]
This seems to be a quite outdated issue, so if nobody has it anymore, I guess we can close it...
