### ISSUE TITLE
Incorrect environment using rails 5 system tests

### ISSUE THREAD

**Issue by kule** [railsconfig/config#208]
Just posting this incase someone else has this - I current gem doesn't appear to be threadsafe, when running the new rails system tests (with rspec) I'd consistently get failures when running the full test suite.  Investigating with pry I'd find that the Settings object was showing the incorrect settings for the current environment - it's like it hadn't merged the current envs settings.

I created my own simplified version of RailsConfig using class instance variables which had the same issue, but storing the settings in Thread.current fixed the issue for me.

**Comment by pkuczynski** [comment]
Maybe you would like to prepare a PR? I am not working with Ruby anymore for the last 3y... :(

**Comment by pkuczynski** [comment]
With the changes from #230 this should not be an issue anymore. @kule would you like to test and confirm?
