### ISSUE TITLE
Feature: Database as config source

### ISSUE THREAD

**Issue by ryanwjackson** [railsconfig/config#236]
# Problem
I am using Config where we have various environments.  We use defaults, environment YAMLs, and ENV vars for overriding.  I am faced with a situation though where my non-technical counterparts want to make changes (i.e. change the video that is used as a background).  Rather than require a deploy, it would be nice to have a way for them to change this.  

# Solution
I have been exploring if one could use a database as an override source for Config.  To be fair, I haven't thought this through fully and figured someone else probably has.  So let me know what I'm missing:

- Create key/value table (with config for table/model name?)
- Specify override order (e.g. `settings.yml` < `envionments/*.yml` < `ENV` < `DB`)
- Config to use cache (e.g. redis) or just use DB lookups
- On app load, build cache which is accessed via (`Settings.foo.bar`)
- Break cache key for value if DB value is added.

# Observations

- Requires a fundamental change of state storage (though this could be a config as well as in you don't have to use a DB cache)
- This increases latency for lookups
- Adds quite a bit of complexity to the gem

# Questions

1. How do we speed this up while allowing changes without app deployments?
1. Do we need a model?
1. Is this the best approach for solving the problem of allowing non-technical people to edit the config without requiring deployments?

**Comment by pkuczynski** [comment]
To be honest with you, I am not a fan of adding DB dependency to config. Feels way to complex and bringing complex db-related dependencies.

Feels like you should manage such settings on your own side. `Config` gem should only be rather used to deliver a common layer of configuration for your app. However if you feel you need things from DB, you should be still able to implement it using https://github.com/railsconfig/config#adding-sources-at-runtime

**Comment by ryanwjackson** [comment]
I agree, it does add a lot of complexity, which is why I think it's worth
figuring out if there's a simpler way to solve the problem.  The issue with
sources at runtime is that if you have a distributed system across multiple
servers, containers, dynos, etc. it becomes a challenge to trigger a
reload.  You would need a shared source across all of them and the ability
to detect/trigger reloads.


--
Ryan Jackson
ryanwjackson@gmail.com

**Comment by pkuczynski** [comment]
What I meant with runtime is you could pull that info from DB on some request parsing middleware... I really would not add such dependency to this gem.

@ pyromaniac @rdubya @supremebeing7 what you think?

**Comment by ryanwjackson** [comment]
Yeah, adding it also gets very confusing given different adaptors, plugging
into the ORM, etc.  I'm with you, but curious if there is a clever way to
change config during runtime across multiple instances.  Obviously would
love a lib to solve my problem rather than building it myself, but also
understand the value of keeping something simple and not overcomplicating
it.


--
Ryan Jackson
ryanwjackson@gmail.com

**Comment by supremebeing7** [comment]
I would agree that this seems out of the realm of this gem. 

I'm not too experienced with distributed systems, but even if this was built into the gem, wouldn't you still run into the issue of needing to trigger a reload when a config value was changed in the DB?

**Comment by rdubya** [comment]
I agree, I see this as a gem for defining static settings for an instance.

If the values can change, they should probably be read from the db somehow each time they are needed (or potentially in a timed cache) otherwise you'll always need some way of triggering an update everywhere that is using the setting. We have some similar things in our system, in some cases we read them from the db every time (if they aren't used frequently or can change frequently) and in others we have an in-memory cache that expires after 1 minute so that we know the changes will propagate everywhere within a minute.

**Comment by pkuczynski** [comment]
As we all agree, I will close this.
