### ISSUE TITLE
Update to use new dry-validation contracts

### ISSUE THREAD

**Issue by ryanwjackson** [railsconfig/config#237]
The dry-validation gem now relies on a new object called a `Contract`: https://dry-rb.org/gems/dry-validation/

These objects incorporate `schemas` and also allow you access to `rules` which make it possible to do conditional validation (e.g. "this should be a string if this other setting is odd").

**In theory**, this should be easy to implement by offering something like:

```ruby
class ConfigContract < Dry::Validation::Contract
  params do
    required(:email).filled(:string)
    required(:age).value(:integer)
  end

  rule(:email) do
    unless /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.match?(value)
      key.failure('has invalid format')
    end
  end

  rule(:age) do
    key.failure('must be greater than 18') if value < 18
  end
end

Config.setup do |config|
  config.dry_validation_contract = ConfigContract
end
```

**Comment by pkuczynski** [comment]
Sounds interesting! Ability to validate config is definitely a nice thing to do. @ryanwjackson would you like to work on this? I suggest we change the option name to `config.validation_contract`

**Comment by ryanwjackson** [comment]
I can take a stab at it.  I assume we want to leave `config.schema` for backwards compatibility, but do you want me to add that `.validation_contract` is the proper way going forward in the README?

**Comment by pkuczynski** [comment]
Yeah, I think we should keep `schema` for backward compatibility and add `config.contract` for the new thing, specifying in the README that use have to options to validate.

What you think?
