### ISSUE TITLE
How to add  a custom environment on Rails?

### ISSUE THREAD

**Issue by DIGITALSQUAD** [railsconfig/config#245]
I want to use a custom environment **production_clone** and added a setting yaml in  /config/settings/production_clone.yml but Settings become nil and raisse NoMethodError.
`Settings.s3_key # => undefined method 's3_key' for nil:NilClass (NoMethodError)`
How can I add ?

**Comment by pkuczynski** [comment]
I suggest to use `local` files as explained here: https://github.com/railsconfig/config#developer-specific-config-files

Otherwise, you can do https://github.com/railsconfig/config#adding-sources-at-runtime

**Comment by DIGITALSQUAD** [comment]
Added settings/production_clone.local.yml  and fixed.
Thanks for your reply.
