### ISSUE TITLE
Settings is not present for rake tasks (rake assets:precompile)

### ISSUE THREAD

**Issue by niedfelj** [railsconfig/config#39]

**Comment by pkuczynski** [comment]
Anyone willing to do a PR for this issue?

**Comment by brunoguerra** [comment]
Sorry @mgraham, I don't remember if I saw this, really sorry. I solved my problem as I told on my comment for single task. It works on this problem context.

@pkuczynski is very old question. My PR https://github.com/railsconfig/config/pull/55 had bugs, perhaps your commit could solved it like a charm https://github.com/railsconfig/config/commit/73aac7c14540ee9cf548a9131d58219cc3f7985c Mentioned by @fredwu. I don't tested it.

I moved to Rails 4 and I never faced this approach again.

**Comment by pkuczynski** [comment]
Got it! I will close this one as its indeed very old.
