### ISSUE TITLE
Tests don't pass with Ruby 1.8

### ISSUE THREAD

**Issue by jlecour** [railsconfig/config#42]
I've tried to run te test suite with Ruby 1.8.7 (REE) and I got this :

(the current commit is ec6f46d870dace3ea5f66bf06a33b16fdc28fe7d)

~/Sandbox/jlecour/rails_config [ree-1.8.7-2012.02][git:fix_symbols?] 
→ be rake                         
/Users/jlecour/.rbenv/versions/ree-1.8.7-2012.02/bin/ruby -S rspec spec/rails_config_spec.rb spec/sources/yaml_source_spec.rb
FF......FF...........FFFF.............

Failures:

  1) RailsConfig should load a basic config file
     Failure/Error: config = RailsConfig.load_files(setting_path("settings.yml"))
     TypeError:
       nil is not a symbol
     # ./lib/rails_config/options.rb:81:in `__convert'
     # ./lib/rails_config/options.rb:79:in `each'
     # ./lib/rails_config/options.rb:79:in `__convert'
     # ./lib/rails_config/options.rb:31:in `load!'
     # ./lib/rails_config.rb:30:in `load_files'
     # ./spec/rails_config_spec.rb:6

  2) RailsConfig should load 2 basic config files
     Failure/Error: config = RailsConfig.load_files(setting_path("settings.yml"), setting_path("settings2.yml"))
     TypeError:
       nil is not a symbol
     # ./lib/rails_config/options.rb:81:in `__convert'
     # ./lib/rails_config/options.rb:79:in `each'
     # ./lib/rails_config/options.rb:79:in `__convert'
     # ./lib/rails_config/options.rb:31:in `load!'
     # ./lib/rails_config.rb:30:in `load_files'
     # ./spec/rails_config_spec.rb:12

  3) RailsConfig should allow overrides
     Failure/Error: config = RailsConfig.load_files(files)
     TypeError:
       nil is not a symbol
     # ./lib/rails_config/options.rb:81:in `__convert'
     # ./lib/rails_config/options.rb:79:in `each'
     # ./lib/rails_config/options.rb:79:in `__convert'
     # ./lib/rails_config/options.rb:31:in `load!'
     # ./lib/rails_config.rb:30:in `load_files'
     # ./spec/rails_config_spec.rb:52

  4) RailsConfig should allow full reload of the settings files
     Failure/Error: RailsConfig.load_and_set_settings(files)
     TypeError:
       nil is not a symbol
     # ./lib/rails_config/options.rb:81:in `__convert'
     # ./lib/rails_config/options.rb:79:in `each'
     # ./lib/rails_config/options.rb:79:in `__convert'
     # ./lib/rails_config/options.rb:31:in `load!'
     # ./lib/rails_config.rb:30:in `load_files'
     # ./lib/rails_config.rb:37:in `load_and_set_settings'
     # ./spec/rails_config_spec.rb:59

  5) RailsConfig Merging hash at runtime should be chainable
     Failure/Error: let(:config) { RailsConfig.load_files(setting_path("settings.yml")) }
     TypeError:
       nil is not a symbol
     # ./lib/rails_config/options.rb:81:in `__convert'
     # ./lib/rails_config/options.rb:79:in `each'
     # ./lib/rails_config/options.rb:79:in `__convert'
     # ./lib/rails_config/options.rb:31:in `load!'
     # ./lib/rails_config.rb:30:in `load_files'
     # ./spec/rails_config_spec.rb:158
     # ./spec/rails_config_spec.rb:162

  6) RailsConfig Merging hash at runtime should preserve existing keys
     Failure/Error: let(:config) { RailsConfig.load_files(setting_path("settings.yml")) }
     TypeError:
       nil is not a symbol
     # ./lib/rails_config/options.rb:81:in `__convert'
     # ./lib/rails_config/options.rb:79:in `each'
     # ./lib/rails_config/options.rb:79:in `__convert'
     # ./lib/rails_config/options.rb:31:in `load!'
     # ./lib/rails_config.rb:30:in `load_files'
     # ./spec/rails_config_spec.rb:158
     # ./spec/rails_config_spec.rb:166
     # ./spec/rails_config_spec.rb:166

  7) RailsConfig Merging hash at runtime should recursively merge keys
     Failure/Error: let(:config) { RailsConfig.load_files(setting_path("settings.yml")) }
     TypeError:
       nil is not a symbol
     # ./lib/rails_config/options.rb:81:in `__convert'
     # ./lib/rails_config/options.rb:79:in `each'
     # ./lib/rails_config/options.rb:79:in `__convert'
     # ./lib/rails_config/options.rb:31:in `load!'
     # ./lib/rails_config.rb:30:in `load_files'
     # ./spec/rails_config_spec.rb:158
     # ./spec/rails_config_spec.rb:170

  8) RailsConfig Merging hash at runtime should rewrite a merged value
     Failure/Error: let(:config) { RailsConfig.load_files(setting_path("settings.yml")) }
     TypeError:
       nil is not a symbol
     # ./lib/rails_config/options.rb:81:in `__convert'
     # ./lib/rails_config/options.rb:79:in `each'
     # ./lib/rails_config/options.rb:79:in `__convert'
     # ./lib/rails_config/options.rb:31:in `load!'
     # ./lib/rails_config.rb:30:in `load_files'
     # ./spec/rails_config_spec.rb:158
     # ./spec/rails_config_spec.rb:175
     # ./spec/rails_config_spec.rb:175

Finished in 0.04651 seconds
38 examples, 8 failures

Failed examples:

rspec ./spec/rails_config_spec.rb:5 # RailsConfig should load a basic config file
rspec ./spec/rails_config_spec.rb:11 # RailsConfig should load 2 basic config files
rspec ./spec/rails_config_spec.rb:50 # RailsConfig should allow overrides
rspec ./spec/rails_config_spec.rb:57 # RailsConfig should allow full reload of the settings files
rspec ./spec/rails_config_spec.rb:161 # RailsConfig Merging hash at runtime should be chainable
rspec ./spec/rails_config_spec.rb:165 # RailsConfig Merging hash at runtime should preserve existing keys
rspec ./spec/rails_config_spec.rb:169 # RailsConfig Merging hash at runtime should recursively merge keys
rspec ./spec/rails_config_spec.rb:174 # RailsConfig Merging hash at runtime should rewrite a merged value
rake aborted!
/Users/jlecour/.rbenv/versions/ree-1.8.7-2012.02/bin/ruby -S rspec spec/rails_config_spec.rb spec/sources/yaml_source_spec.rb failed

**Comment by fredwu** [comment]
Hi, given ruby 1.8.x has been EOL'ed for a while, unless anyone wants to contribute patches I'm afraid I'm not going to do anything to it... Sorry.
