### ISSUE TITLE
OH GOD CHANGE THE NAME!

### ISSUE THREAD

**Issue by jc00ke** [railsconfig/config#48]
`Settings` is the name of the constant yet the gem name is `rails_config`? Ahhh, this hurts so much!

ps: I don't expect this issue to be taken seriously, as it's mainly a complaint of seeing one thing (`Settings`) and not knowing where it originates (`rails_config`).

**Comment by pkuczynski** [comment]
Any other suggested names for the gem and/or global variable? Things like 'config', 'settings' are already taken on Ruby Gems...

**Comment by fredwu** [comment]
The gem has now been renamed to `Config`. :)

**Comment by jc00ke** [comment]
:+1:

**Comment by pkuczynski** [comment]
@fredwu have you also change the variable name from `Settings` to `Config`? And can you make me an owner on the new gem too, like I was on rails_config? :)

**Comment by fredwu** [comment]
@pkuczynski Of course! Done! :)
