### ISSUE TITLE
Method to specify some settings as read-only

### ISSUE THREAD

**Issue by reagleton** [railsconfig/config#71]
It would be nice to have a method/feature that allows us to specify some settings as read-only, particularly as when I display the settings, there is a key/value that appears for each section as `modifiable: true`. It seems that this is something to do with the options so if a shortcut could be provided to allow us to mark a section as modifiable or not at runtime, it would make it easier to manage sections.

**Comment by pkuczynski** [comment]
I think adding an option per section is too much and overcomplicated. What we could do is (based on a setting) assume that certain naming convention should make individual setting read only. One way would be to follow Ruby const convention by writing read-only settings using CAPS. What you think?

**Comment by pkuczynski** [comment]
Closing due lack of feedback.
