### ISSUE TITLE
Missing keys should raise an error

### ISSUE THREAD

**Issue by janko-m** [railsconfig/config#77]
This really seemed like a perfect gem for me. I extactly wanted specification for different environments in separate files.

However, there is one major design flaw. Accessing an option that wasn't set in the YAML files should raise a `NoMethodError`. That is, `RailsConfig::Options` shouldn't be an `OpenStruct`. Otherwise there is no way to guard yourself from typos, since there is no way to determine whether you made one. And that can cause really hard-to-find bugs (e.g. boolean value like `Settings.use_secure_sever`).

**Comment by shlima** [comment]
+1

**Comment by gauda** [comment]
+1

**Comment by shlima** [comment]
@pkuczynski please provide something like a `fetch` method

**Comment by pkuczynski** [comment]
This is the same issue as described in #43. I will have a look...
