### ISSUE TITLE
Add more YAML files at load time (not runtime)

### ISSUE THREAD

**Issue by BattleBrisket** [railsconfig/config#80]
I'd like to add more files to the RailsConfig file load chain. I know what these files will be in advance, so I'd rather avoid loading them at runtime. Is there some syntax available that works like the following...

``` ruby
RailsConfig.setup do |config|
  config.add_file(Rails.root.join("config", "some_additional_stuff.yml")
end
```

I didn't see anything whilst digging through the code, though I am admittedly n00bish when it comes to parsing out gems.

**Comment by 3den** [comment]
@jacquescrocker it would be nice to have it as a config, following rails standards. The current approach works but fells weird coz it has to load, add more files, and reload again.

**Comment by pkuczynski** [comment]
@3den feel free to create new issue and describe your approach in more details.
