### ISSUE TITLE
question: reference settings in other settings?

### ISSUE THREAD

**Issue by tony-kerz** [railsconfig/config#91]
i'd like to do something like this (with any syntax) in a config file:

```
world: 'world'
hello: <%= "hello #{world}" %>
```

i tried a couple of angles with no luck, is it possible?

regards,
tony.

**Comment by jiggneshhgohel** [comment]
+1

**Comment by pkuczynski** [comment]
ERB syntax should already work in YAML files, however you would not be able to reference other elements of YAML inside the same file. You can only define YAML aliases and refer to them in other places (http://yaml.org/YAML_for_ruby.html#aliases_and_anchors), but this would not achieve what you expect.

The only way I can see this working is storing separate setting and implementing gluing logic in your code.

I believe trying to work out a solution for this issue would go beyond the merits of this gem so I will close it for now...
