### ISSUE TITLE
Settings not updated even with restart

### ISSUE THREAD

**Issue by gauthier-delacroix** [railsconfig/config#92]
Hi !
I'm a new user of RailsConfig and maybe I miss something but my settings aren't updated when I restart my Rails console (dev mode), and I have to use `Settings.reload!` each time I change a setting:
````
# rails c
Loading development environment (Rails 4.1.6)
[1] pry(main)> Settings
{
  my_setting => 1
}
[2] pry(main)> exit
````
Change YML file with `my_setting: 2`:
````
# rails c
Loading development environment (Rails 4.1.6)
[1] pry(main)> Settings
{
  my_setting => 1
}
[2] pry(main)> Settings.reload!
{
  my_setting => 2
}
````
Are settings cached somewhere even between different console sessions ?
I know `Settings.reload!` is faster that relaunching console, but having a fresh console session with obsolete settings is quite disturbing...

I'm using 0.5.0.beta1 with Rails 4.1.6. Version 0.4.2 didn't even load my settings (empty hash).

Thanks !

**Comment by fredwu** [comment]
Sounds like we're all good here, closing. :)

**Comment by albertnetymk** [comment]
Does it make sense to add @stevschmid 's snippet to the README? I have to search through the issues to find out why my settings are not available in rails console.

**Comment by sgnl** [comment]
I ran into this and with guidance from the accepted answer on this Stackoverflow [question](https://stackoverflow.com/a/30270376/2612640).

I had to kill the spring process running in the background. Once I did, the Settings constant updated its values.

Then I added the code mentioned by `gauthier-delacroix` and it's working now without having to manually fuss with Spring.

Thanks!
