### ISSUE TITLE
No settings loaded in Rails 4.1.6

### ISSUE THREAD

**Issue by yoonwaiyan** [railsconfig/config#94]
I've added a setting in config/settings.yml like this
`hello: "All"`
Tested that config in rails console but `Settings.hello` returns nil. 
The output in `Settings` is `#<RailsConfig::Options>`.
I tried the solution provided in Issue #92 but it's not working.
Anyone knows how to make this work? Thanks in advance.

**Comment by iHiD** [comment]
I'm seeing this too. Doing a `Settings.reload!` works. 0.5.0.beta1 works too.

**Comment by MattBillock** [comment]
I'm seeing the same thing - the settings do not load in rails console when first run. Everything seems to work fine after a Settings.reload! - restarting the console after that happens results in the settings loading correctly. Is the beta release stable enough to be used in production, or scheduled to become an official release? Any idea when this issue will be addressed in an official release?

**Comment by jiongye** [comment]
I am having the same issue. it seems like the Spring gem cached the Settings. When I turn off the Spring gem, everything works as expected.

**Comment by akhramov** [comment]
Yes, Spring is the reason. Thanks, @jiongye!

**Comment by fredwu** [comment]
Sounds like we're all good here, closing. :)
