### ISSUE TITLE
How to prepend engine's config to rails-app?

### ISSUE THREAD

**Issue by fuminori-ido** [railsconfig/config#98]
I would like to use rails_config both engine (let me say 'MyEngine' here) and rails-app which uses the engine.  Also, I would like to overwrite MyEngine's settings at rails-app settings.  Is this possible?

The discussion http://stackoverflow.com/questions/20597501/how-to-integrate-rails-config-under-rails-engine says just integrate engine's settings to rails-app engine, but MyEngine's settings cannot be overwritten by rails-app.  It would be helpful to show how to do that.

**Comment by pkuczynski** [comment]
I think you already received pretty good answer on the Stackoverflow...
